[package]
name = "scottbea/spatialhashing"
description = "Create 'spatial hashes' by converting world positions to 12 octal characters and vice versa within a defined cubic size in studs. This size can be configured by using the SetBits() function to specificy the number of bits (k) used in the voxel size. The size in studs is given by n = 2**k.  The default size in bits is 2, so the default voxel size is Vector3(4, 4, 4). This library allows you to map multiple nearby world positions in space to the same hash to understand their proximity in time O(1). The main use for this library is to implement very high-speed geofencing and proximity detection features. For example, any given 3D bounds could be represented by 1 or more  spatial hashes which could be tracked in a table."
license = "MIT"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "3.2.0"
exclude = [
	"docs", ".moonwave", "test",
	"SpatialHashing.rbxm", "SpatialHashing.rbxmx",
	".gitignore", "foreman.toml",
]

[dependencies]